{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "billpiggy.fullname" . }}
  labels:
    {{- include "billpiggy.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseURL | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  BOOTSTRAP_SUPER_ADMIN_EMAIL: {{ .Values.secrets.bootstrapSuperAdminEmail | quote }}
  BOOTSTRAP_SUPER_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapSuperAdminPassword | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openAIAPIKey | quote }}
  SMTP_ADDRESS: {{ .Values.secrets.smtpAddress | quote }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  SMTP_FROM: {{ .Values.secrets.smtpFrom | quote }}
  MINIO_ENDPOINT: {{ .Values.secrets.minioEndpoint | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  MINIO_BUCKET: {{ .Values.secrets.minioBucket | quote }}
  MINIO_USE_SSL: {{ .Values.secrets.minioUseSSL | quote }}
{{- end }}
